#!/usr/bin/env python3

import os
import sys

# Set environment variables for libffi
os.environ['LDFLAGS'] = '-L/usr/local/opt/libffi/lib'
os.environ['CPPFLAGS'] = '-I/usr/local/opt/libffi/include'
os.environ['PKG_CONFIG_PATH'] = '/usr/local/opt/libffi/lib/pkgconfig'

try:
    print("Testing WeasyPrint import...")
    from weasyprint import HTML
    print("✅ WeasyPrint imported successfully!")
    
    print("Testing HTML to PDF conversion...")
    html_content = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Test PDF</title>
    </head>
    <body>
        <h1>Hello World!</h1>
        <p>This is a test PDF generated by WeasyPrint.</p>
    </body>
    </html>
    """
    
    pdf_bytes = HTML(string=html_content).write_pdf()
    print(f"✅ PDF generated successfully! Size: {len(pdf_bytes)} bytes")
    
    # Save test PDF
    with open('test_output.pdf', 'wb') as f:
        f.write(pdf_bytes)
    print("✅ Test PDF saved as 'test_output.pdf'")
    
except ImportError as e:
    print(f"❌ Import error: {e}")
    sys.exit(1)
except Exception as e:
    print(f"❌ Error: {e}")
    sys.exit(1)
